name: Update IPTV List

on:
  schedule:
    - cron: '18 2 * * *'  # UTC 02:18 (北京时间 10:18)
    - cron: '18 6 * * *'  # UTC 06:18 (北京时间 14:18)
    - cron: '18 10 * * *' # UTC 10:18 (北京时间 18:18)
    - cron: '18 14 * * *' # UTC 14:18 (北京时间 22:18)
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Python Script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add simple.m3u simple.txt
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            COMMIT_DATE=$(TZ="Etc/GMT+8" date +"%Y-%m-%d %H:%M")
            git commit -m "🔄 Auto update - $COMMIT_DATE"
            git push
          fi
